#! /bin/sh

# keymaps
sxhkd &

# display manager locker
#light-locker &

# wallpaper
#~/.fehbg

# bar
~/.config/polybar/launch.sh

# KDE connect
#indicator-kdeconnect &

# NetworkManager tray
nm-applet &

# Notifications
pkill dunst
dunst

# set typematic delay
xset r rate 200 60

bspc monitor eDP-1 -d I II III IV
bspc monitor DP-1 -d I II III
bspc monitor DP-2 -d I II III
bspc monitor DP-3 -d I II III
bspc monitor DP-1-1 -d I II III
bspc monitor DP-1-2 -d I II III
bspc monitor DP-1-3 -d I II III

bspc config border_width         1
#bspc config window_gap          24
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
