#! /bin/sh

# keymaps
sxhkd &

# display manager
light-locker &

# wallpaper
~/.fehbg

# bar
~/.config/polybar/launch.sh

# KDE connect
indicator-kdeconnect &

# NetworkManager tray 
nm-applet &

# set typematic delay
xset r rate 200 60

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X XI XII

bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
